# Generated by Django 4.1.7 on 2023-03-03 18:05

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('producto', '0002_remove_producto_categoria_categoria_producto_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='punto',
            name='cantidad',
        ),
        migrations.RemoveField(
            model_name='punto',
            name='producto',
        ),
        migrations.CreateModel(
            name='Stock',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fecha_creacion', models.DateTimeField(auto_now_add=True)),
                ('cantidad', models.IntegerField()),
                ('producto', models.ManyToManyField(related_name='producto_stock', to='producto.producto')),
                ('punto', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='producto.punto')),
            ],
        ),
    ]
