# Generated by Django 4.1.7 on 2023-03-03 18:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('producto', '0003_remove_punto_cantidad_remove_punto_producto_stock'),
    ]

    operations = [
        migrations.AddField(
            model_name='punto',
            name='direccion',
            field=models.CharField(blank=True, max_length=100),
        ),
    ]
