# Generated by Django 4.1.7 on 2023-03-03 18:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('producto', '0004_punto_direccion'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='categoria',
            name='producto',
        ),
        migrations.AddField(
            model_name='producto',
            name='categoria',
            field=models.ManyToManyField(related_name='producto_categoria', to='producto.categoria'),
        ),
    ]
