# Generated by Django 4.1.7 on 2023-03-03 18:16

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('provedor', '0002_alter_provedor_correo_alter_provedor_direccion_and_more'),
        ('producto', '0005_remove_categoria_producto_producto_categoria'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='producto',
            name='provedor',
        ),
        migrations.AddField(
            model_name='producto',
            name='provedor',
            field=models.ForeignKey(default=1, help_text='Provedor del producto', on_delete=django.db.models.deletion.CASCADE, related_name='provedor', to='provedor.provedor'),
            preserve_default=False,
        ),
    ]
