# Generated by Django 4.1.7 on 2023-03-03 18:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('producto', '0002_remove_producto_categoria_categoria_producto_and_more'),
        ('ventas', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='venta',
            name='producto',
            field=models.ManyToManyField(help_text='Producto de la venta', related_name='producto_venta', to='producto.producto'),
        ),
    ]
