# Generated by Django 4.1.7 on 2023-03-03 20:13

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('ventas', '0003_venta_usuario'),
    ]

    operations = [
        migrations.RenameField(
            model_name='venta',
            old_name='monto_final',
            new_name='precio_final',
        ),
        migrations.RemoveField(
            model_name='venta',
            name='fecha_creacion',
        ),
        migrations.RemoveField(
            model_name='venta',
            name='usuario',
        ),
        migrations.AddField(
            model_name='venta',
            name='cantidad',
            field=models.IntegerField(default=1, help_text='cantidad de productos en la venta'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='venta',
            name='precio_unidad',
            field=models.IntegerField(default=1),
            preserve_default=False,
        ),
        migrations.CreateModel(
            name='Factura',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fecha_creacion', models.DateTimeField(auto_now_add=True)),
                ('descuento', models.CharField(max_length=10)),
                ('monto_final', models.IntegerField()),
                ('usuario', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='usuario', to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
