# Generated by Django 4.1.7 on 2023-03-03 20:28

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('ventas', '0004_rename_monto_final_venta_precio_final_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='venta',
            name='factura',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='ventas.factura'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='factura',
            name='descuento',
            field=models.CharField(blank=True, max_length=10),
        ),
        migrations.AlterField(
            model_name='factura',
            name='id',
            field=models.BigAutoField(primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='venta',
            name='descuento',
            field=models.CharField(blank=True, max_length=10),
        ),
        migrations.AlterField(
            model_name='venta',
            name='id',
            field=models.BigAutoField(primary_key=True, serialize=False),
        ),
    ]
