# Generated by Django 4.1.7 on 2023-03-03 17:27

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Provedor',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tipo_id', models.CharField(choices=[('0', 'Cedula'), ('1', 'Rut')], help_text='Tipo de id', max_length=10)),
                ('provedor_id', models.CharField(help_text='cedula o ruth del provedor', max_length=10, unique=True)),
                ('nombre', models.CharField(help_text='Nombre del producto', max_length=100)),
                ('telefono', models.JSONField()),
                ('direccion', models.CharField(max_length=100)),
                ('correo', models.CharField(max_length=100)),
                ('pagina_web', models.CharField(max_length=100)),
                ('fecha_creacion', models.DateTimeField(auto_now_add=True)),
            ],
        ),
    ]
