# Generated by Django 4.1.7 on 2023-03-03 18:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('provedor', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='provedor',
            name='correo',
            field=models.CharField(blank=True, max_length=100),
        ),
        migrations.AlterField(
            model_name='provedor',
            name='direccion',
            field=models.CharField(blank=True, max_length=100),
        ),
        migrations.AlterField(
            model_name='provedor',
            name='pagina_web',
            field=models.CharField(blank=True, max_length=100),
        ),
    ]
